version: "3.8"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /Users/sahafid/Desktop/Inception/srcs/wordpress
      o: bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /Users/sahafid/Desktop/Inception/srcs/mariadb
      o: bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
     - ./web/wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wp-php
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - ./web/wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    image: mariadb:42
    volumes:
      - ./web/mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

# services:
#   nginx:
#     build: requirements/nginx/.
#     container_name: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./web:/var/www/html
#   wordpress:
#     build: requirements/wordpress/.
#     container_name: wp-php
#     volumes:
#       - ./web:/var/www/html
#   mariadb:
#     build: requirements/mariadb/.
#     container_name: mariadb
# networks:
#   inception:
#     name: inception
